# Generated by Django 4.2.5 on 2023-09-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.CharField(help_text='Course ID', max_length=10)),
                ('CourseName', models.CharField(help_text='Course Name', max_length=50)),
                ('YearsRequired', models.IntegerField(help_text='List of Years Required')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DegreeName', models.CharField(help_text='Degree Name', max_length=75)),
                ('DegreeYear', models.IntegerField(help_text='Degree Year')),
                ('UniversityName', models.CharField(help_text='University Name', max_length=75)),
                ('DepartmentName', models.CharField(help_text='Department Name', max_length=75)),
                ('MajorName', models.CharField(help_text='Major Name', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Department_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentID', models.CharField(help_text='Department ID', max_length=10)),
                ('DepartmentName', models.CharField(help_text='Department Name', max_length=50)),
                ('CourseID', models.CharField(help_text='Course ID', max_length=10)),
                ('CourseName', models.CharField(help_text='Course Name', max_length=50)),
                ('YearsRequired', models.IntegerField(help_text='List of Years Required')),
            ],
        ),
        migrations.CreateModel(
            name='Major_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MajorName', models.CharField(help_text='Major Name', max_length=50)),
                ('CourseID', models.CharField(help_text='Course ID', max_length=10)),
                ('CourseName', models.CharField(help_text='Course Name', max_length=50)),
                ('YearsRequired', models.IntegerField(help_text='List of Years Required')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WTID', models.IntegerField(help_text='WT ID')),
                ('FirstName', models.CharField(help_text='First Name', max_length=30)),
                ('LastName', models.CharField(help_text='Last Name', max_length=30)),
                ('DegreeName', models.CharField(help_text='Degree Name', max_length=75)),
                ('DegreeYear', models.IntegerField(help_text='Degree Year')),
                ('TransferStudent', models.BooleanField(default=False, help_text='Transfer Student')),
                ('CoursesCompleted', models.CharField(help_text='List of Courses Completed', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='University_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniversityName', models.CharField(help_text='University Name', max_length=50)),
                ('CourseID', models.CharField(help_text='Course ID', max_length=10)),
                ('CourseName', models.CharField(help_text='Course Name', max_length=50)),
                ('YearsRequired', models.IntegerField(help_text='List of Years Required')),
            ],
        ),
    ]
