# Generated by Django 4.2.5 on 2023-10-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0002_alter_core_requirements_coursename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='core_requirements',
            old_name='CourseID',
            new_name='CoreCourseID',
        ),
        migrations.RenameField(
            model_name='core_requirements',
            old_name='CourseName',
            new_name='CoreCourseName',
        ),
    ]
