# Generated by Django 4.2.5 on 2023-10-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0003_rename_courseid_core_requirements_corecourseid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department_requirements',
            old_name='CourseID',
            new_name='DepCourseID',
        ),
        migrations.RenameField(
            model_name='major_requirements',
            old_name='CourseID',
            new_name='MajCourseID',
        ),
        migrations.RenameField(
            model_name='university_requirements',
            old_name='CourseID',
            new_name='UniCourseID',
        ),
        migrations.RemoveField(
            model_name='department_requirements',
            name='CourseName',
        ),
        migrations.RemoveField(
            model_name='major_requirements',
            name='CourseName',
        ),
        migrations.RemoveField(
            model_name='university_requirements',
            name='CourseName',
        ),
        migrations.AddField(
            model_name='department_requirements',
            name='DepCourseName',
            field=models.CharField(help_text='Course Name', max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='major_requirements',
            name='MajCourseName',
            field=models.CharField(help_text='Course Name', max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='university_requirements',
            name='UniCourseName',
            field=models.CharField(help_text='Course Name', max_length=75, null=True),
        ),
    ]
