# Generated by Django 4.2.5 on 2023-11-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0004_rename_courseid_department_requirements_depcourseid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.AlterField(
            model_name='university_requirements',
            name='UniversityName',
            field=models.CharField(help_text='University Name', max_length=75),
        ),
    ]
